/// Regenerates `shared/fixtures/scoring-vectors.json`, the single set of golden
/// vectors that both the TypeScript tests and `ScoringParity.t.sol` assert
/// against. Run with `pnpm --filter @moment-grid/scoring gen:vectors` whenever
/// the prediction set changes, and commit the diff deliberately.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import {
  eventsToWindowBitmaps,
  gridToMomentIds,
  LINE_MASKS,
  MatchEvent,
  PREDICTION_POOLS,
  PredictionId,
  replayMatchEvents,
  scoreMomentIdsAgainstWindows,
  TIER_POOLS,
} from "../src";

type Vector = {
  name: string;
  grid: number[];
  windows: string[];
  mask: number;
  lines: number;
  valid: boolean;
};

const hex = (value: bigint) => `0x${value.toString(16)}`;

const QUICK_GRID: PredictionId[] = [
  "HOME_TWO_SHOTS_30",
  "CARD_30_60",
  "TWO_SUBS_AFTER_60",
  "HOME_SCORES_FIRST",
  "VAR_30_60",
  "BOTH_SCORE_FULL_TIME",
  "PENALTY_BEFORE_30",
  "PENALTY_30_60",
  "GOAL_AFTER_80",
];

const FIRST_OF_EACH_POOL: PredictionId[] = Array.from(
  { length: 9 },
  (_, cell) => PREDICTION_POOLS[Math.floor(cell / 3)][cell % 3][0],
);

const CHAOTIC_MATCH: MatchEvent[] = [
  { minute: 3, eventType: "AWAY_GOAL" },
  { minute: 8, eventType: "HOME_SHOT" },
  { minute: 9, eventType: "HOME_SHOT" },
  { minute: 11, eventType: "PENALTY_AWARDED" },
  { minute: 14, eventType: "GOAL_OVERTURNED" },
  { minute: 21, eventType: "CORNER" },
  { minute: 26, eventType: "CORNER" },
  { minute: 33, eventType: "VAR_REVIEW" },
  { minute: 44, eventType: "HOME_GOAL" },
  { minute: 52, eventType: "SUBSTITUTE_GOAL", team: "away" },
  { minute: 55, eventType: "SUBSTITUTION" },
  { minute: 58, eventType: "SUBSTITUTION" },
  { minute: 77, eventType: "RED_CARD" },
  { minute: 84, eventType: "HOME_GOAL" },
  { minute: 92, eventType: "EXTRA_TIME" },
];

/// Window bitmaps that mark exactly the given cells for the given grid. Every
/// moment id is distinct, so setting one cell's bit cannot light up another.
function windowsMarking(momentIds: number[], cells: readonly number[]): [bigint, bigint, bigint] {
  const windows: [bigint, bigint, bigint] = [0n, 0n, 0n];
  for (const cell of cells) windows[cell % 3] |= 1n << BigInt(momentIds[cell]);
  return windows;
}

function vectorFrom(name: string, grid: PredictionId[], windows: [bigint, bigint, bigint]): Vector {
  const momentIds = gridToMomentIds(grid);
  const score = scoreMomentIdsAgainstWindows(momentIds, windows, TIER_POOLS);
  return {
    name,
    grid: momentIds,
    windows: windows.map(hex),
    mask: score.markedMask,
    lines: score.completedLines,
    valid: score.validGrid,
  };
}

const cellsOf = (lineMask: number) => [...Array(9).keys()].filter((cell) => (lineMask & (1 << cell)) !== 0);

const quickMomentIds = gridToMomentIds(QUICK_GRID);

const vectors: Vector[] = [
  vectorFrom("quick grid vs shipped replay fixture", QUICK_GRID, eventsToWindowBitmaps(replayMatchEvents())),
  vectorFrom("quick grid vs chaotic match", QUICK_GRID, eventsToWindowBitmaps(CHAOTIC_MATCH)),
  vectorFrom("first-of-each-pool vs shipped replay fixture", FIRST_OF_EACH_POOL, eventsToWindowBitmaps(replayMatchEvents())),
  vectorFrom("every cell marked - all eight lines", QUICK_GRID, windowsMarking(quickMomentIds, [...Array(9).keys()])),
  vectorFrom("nothing marked - zero lines", QUICK_GRID, [0n, 0n, 0n]),
  ...LINE_MASKS.map((lineMask, index) =>
    vectorFrom(`line ${index} in isolation`, QUICK_GRID, windowsMarking(quickMomentIds, cellsOf(lineMask))),
  ),
  vectorFrom("two cells of a row - no line", QUICK_GRID, windowsMarking(quickMomentIds, [0, 1])),
  vectorFrom("crossing row and column - two lines", QUICK_GRID, windowsMarking(quickMomentIds, [0, 1, 2, 3, 6])),
];

const payload = {
  $comment:
    "Generated by shared/scoring/scripts/generate-parity-vectors.ts. Asserted by shared/scoring (TypeScript) and contracts/test/ScoringParity.t.sol (Solidity). Do not edit by hand.",
  tierPools: TIER_POOLS.map(hex),
  count: vectors.length,
  cases: vectors,
};

const target = resolve(__dirname, "../../fixtures/scoring-vectors.json");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`);

console.log(`Wrote ${vectors.length} parity vectors to ${target}`);
for (const vector of vectors) {
  console.log(`  ${vector.name.padEnd(46)} mask=0x${vector.mask.toString(16).padStart(3, "0")} lines=${vector.lines}`);
}
